<?php /** @var $this Emico_Tweakwise_Block_Catalog_Layer_Facet_Attribute */ ?>
<?php if($this->isVisible()): ?>
    <?php $_settings = $this->getFacetSettings(); ?>
    <dt class="<?php echo $_settings->getIsCollapsible() ? 'collapsible' : ''; echo $_settings->getIsCollapsed() ? ' collapsed' : ''; ?>">
        <?php if($_settings->getIsCollapsible()): ?>
            <div class="arrow"></div>
        <?php endif; ?>
        <?php echo $this->__($_settings->getTitle()) ?>
    </dt>
    <dd class="<?php echo $_settings->getIsCollapsed() ? 'hidden' : ''; ?><?php echo $_settings->getNumberOfColumns() > 0 ? ' columns-' . $_settings->getNumberOfColumns() : ''; ?>">
        <?php if($_settings->getIsInfoVisible() && $_settings->getInfoText()): ?>
            <span class="helptext"><?php echo $this->__($_settings->getInfoText()); ?></span>
        <?php endif; ?>


        <?php $_attributes = $this->getAttributes(); ?>
        <?php $_numberOfShownAttributes = 0; ?>
        <ol>
            <?php foreach ($_attributes as $_item): ?>
                <?php $_showLink = !$_item->getIsSelected() || $this->isCheckbox(); ?>
                <li class="<?php echo $_item->getIsSelected() ? 'active' : 'inactive'; echo ($_numberOfShownAttributes >= $_settings->getNumberOfShownAttributes()) ? ' hidden' : ''; echo $this->isCheckbox() ? ' checkbox' : ''; ?>">
                    <a<?php if($_showLink): ?> href="<?php echo $this->escapeUrl($this->getFacetUrl($_item)) ?>"<?php endif; ?> title="<?=$this->escapeHtml($this->getItemTitle($_item))?>"<?=$this->getHrefAttributes()?>>
                        <?php echo $this->escapeHtml($this->getItemTitle($_item)); ?>
                        <?php if ($_settings->getIsNumberOfResultVisible()): ?>
                            (<?php echo $_item->getNumberOfResults() ?>)
                        <?php endif; ?>
                    </a>
                </li>
                <?php $_numberOfShownAttributes += 1 ?>
            <?php endforeach ?>
            <?php if($this->showMoreText()): ?>
                <li class="more-less-links">
                    <a href="#" class="more-link"><?php echo $this->__($_settings->getExpandText()); ?></a>
                    <a href="#" class="less-link hidden"><?php echo $this->__($_settings->getCollapseText()); ?></a>
                </li>
            <?php endif; ?>
        </ol>
    </dd>
<?php endif; ?>
