<?php /** @var $this Emico_Tweakwise_Block_Catalog_Layer_Facet_Tree_Items */ ?>
<?php $_attributes = $this->getAttributes(); ?>
<?php $_settings = $this->getFacetSettings(); ?>
<ol>
    <?php foreach ($_attributes as $_item): /** @var $_item Emico_Tweakwise_Model_Bus_Type_Attribute */ ?>
        <?php $_showLink = $this->isShowLink($_item);

        if($this->getShowOnlyActiveCategories() && (!$_item->getIsSelected() && !$_item->getRender()))
        {
            continue;
        }

        ?>
        <li class="<?php echo $_item->getIsSelected() ? 'active' : 'inactive'; echo $this->isMoreItem($_item) ? ' hidden' : ''; echo $this->isCheckbox() ? ' checkbox' : ''; ?>">
            <a<?php if($_showLink): ?> href="<?php echo $this->escapeUrl($this->getFacetUrl($_item)) ?>"<?php endif; ?>>
                <?php echo $this->getItemTitle($_item); ?>
                <?php if ($_settings->getIsNumberOfResultVisible()): ?>
                    (<?php echo $_item->getNumberOfResults() ?>)
                <?php endif; ?>
            </a>

            <?php if($_item->getChildren()): ?>
                <?php echo $this->getChildrenTreeHtml($_item); ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>